---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gardener.cloud:vsphere-csi-syncer
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gardener.cloud:vsphere-csi-syncer
subjects:
  - kind: User
    name: gardener.cloud:vsphere-csi-syncer
roleRef:
  kind: ClusterRole
  name: gardener.cloud:vsphere-csi-syncer
  apiGroup: rbac.authorization.k8s.io