images:
  csi-attacher: image-repository:image-tag
  csi-provisioner: image-repository:image-tag
  packet-storage-interface: image-repository:image-tag
podAnnotations: {}
replicas: 1
attacherResources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 30m
    memory: 50Mi
provisionerResources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 30m
    memory: 50Mi
diskpluginResources:
  requests:
    cpu: 20m
    memory: 50Mi
  limits:
    cpu: 50m
    memory: 80Mi
kubernetesVersion: v1.13.0
