apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-provider-alicloud
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-provider-alicloud
    helm.sh/chart: gardener-extension-provider-alicloud
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-provider-alicloud
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.imageVectorOverwrite }}
        checksum/configmap-provider-alicloud-imagevector-overwrite: {{ include (print $.Template.BasePath "/configmap-imagevector-overwrite.yaml") . | sha256sum }}
        {{- end}}
        checksum/configmap-gardener-extension-provider-alicloud-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: gardener-extension-provider-alicloud
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-provider-alicloud
      containers:
      - name: gardener-extension-provider-alicloud
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - provider-alicloud-controller-manager
        - --config-file=/etc/gardener-extension-provider-alicloud/config/config.yaml
        - --infrastructure-max-concurrent-reconciles={{ .Values.controllers.infrastructure.concurrentSyncs }}
        - --infrastructure-ignore-operation-annotation={{ .Values.controllers.infrastructure.ignoreOperationAnnotation }}
        - --worker-max-concurrent-reconciles={{ .Values.controllers.worker.concurrentSyncs }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.imageVectorOverwrite }}
        - name: IMAGEVECTOR_OVERWRITE
          value: /charts_overwrite/images_overwrite.yaml
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /etc/gardener-extension-provider-alicloud/config
        {{- if .Values.imageVectorOverwrite }}
        - name: extension-imagevector-overwrite
          mountPath: /charts_overwrite/
          readOnly: true
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: gardener-extension-provider-alicloud-configmap
          defaultMode: 420
      {{- if .Values.imageVectorOverwrite }}
      - name: extension-imagevector-overwrite
        configMap:
          name: gardener-extension-provider-alicloud-imagevector-overwrite
          defaultMode: 420
      {{- end }}