---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-provider-alicloud
  labels:
    app.kubernetes.io/name: gardener-extension-provider-alicloud
    helm.sh/chart: gardener-extension-provider-alicloud
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - clusters
  - infrastructures
  - infrastructures/status
  - workers
  - workers/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - provider-alicloud-leader-election
  verbs:
  - get
  - watch
  - update
  - patch
- apiGroups:
  - ""
  - apps
  - batch
  - rbac.authorization.k8s.io
  - apiextensions.k8s.io
  resources:
  - namespaces
  - events
  - secrets
  - endpoints
  - configmaps
  - deployments
  - services
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  - jobs
  - pods
  - pods/log
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - machine.sapcloud.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener-extension-provider-alicloud
  labels:
    app.kubernetes.io/name: gardener-extension-provider-alicloud
    helm.sh/chart: gardener-extension-provider-alicloud
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener-extension-provider-alicloud
subjects:
- kind: ServiceAccount
  name: gardener-extension-provider-alicloud
  namespace: {{ .Release.Namespace }}
