---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packet-cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: packet-cloud-controller-manager
    garden.sapcloud.io/role: controlplane
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: packet-cloud-controller-manager
  template:
    metadata:
      labels:
        app: packet-cloud-controller-manager
        garden.sapcloud.io/role: controlplane
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/from-prometheus: allowed
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: cloud-controller-manager
        image: {{ index .Values.images "cloud-controller-manager" }}
        imagePullPolicy: IfNotPresent
        command:
          - ./packet-cloud-controller-manager
          - --cloud-provider=packet
          - --leader-elect=false
          - --allow-untagged-cloud=true
          - --kubeconfig=/var/lib/cloud-controller-manager/kubeconfig
        env:
        - name: PACKET_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudprovider
              key: apiToken
        - name: PACKET_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: cloudprovider
              key: projectID
        ports:
        # Packet's CCM is based on K8S 1.11 and uses 10253 port by default.
        - containerPort: 10253
          name: metrics
          protocol: TCP
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: cloud-controller-manager
          mountPath: /var/lib/cloud-controller-manager
      volumes:
      - name: cloud-controller-manager
        secret:
          secretName: cloud-controller-manager
