{{- if eq .Values.gardener.seed.provider "vsphere" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
  labels:
{{ include "labels" . | indent 4 }}
provisioner: kubernetes.io/vsphere-volume
allowVolumeExpansion: true
parameters:
  plan: standard
{{- end }}
