apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-networking-calico
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-networking-calico
    helm.sh/chart: gardener-extension-networking-calico
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-networking-calico
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.imageVectorOverwrite }}
      annotations:
        checksum/configmap-network-imagevector-overwrite: {{ include (print $.Template.BasePath "/configmap-imagevector-overwrite.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/name: gardener-extension-networking-calico
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-networking-calico
      containers:
      - name: gardener-extension-networking-calico
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - networking-calico-controller-manager
        - --max-concurrent-reconciles={{ .Values.controller.concurrentSyncs }}
        - --ignore-operation-annotation={{ .Values.controller.ignoreOperationAnnotation }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.imageVectorOverwrite }}
        - name: IMAGEVECTOR_OVERWRITE
          value: /charts_overwrite/images_overwrite.yaml
        {{- end }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
        {{- if .Values.imageVectorOverwrite }}
        volumeMounts:
        - name: imagevector-overwrite
          mountPath: /charts_overwrite/
          readOnly: true
        {{- end }}
      {{- if .Values.imageVectorOverwrite }}
      volumes:
      - name: imagevector-overwrite
        configMap:
          name: {{ include "name" . }}-imagevector-overwrite
          defaultMode: 420
      {{- end }}
